apiVersion: apps/v1
kind: Deployment
metadata:
  name: xplan-plu-services
  labels:
    app: xplan-plu-services
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: xplan-plu-services
  template:
    metadata:
      labels:
        app: xplan-plu-services
    spec:
      containers:
        - name: xplan-plu-services
          image: grit/xplan-services-inspireplu-docker:4.2-SNAPSHOT
          env:
            - name: TZ
              value: "Europe/Berlin"
            - name: JAVA_OPTS
              value: "-Xmx$(MEMORY_REQUESTED_PLU)m"
          volumeMounts:
            - mountPath: /root/.deegree
              name: xplan-plu-workspace
              subPath: plu-workspace
              readOnly: true
      initContainers:
        - name: init-volume-plu
          image: grit/xplan-init:4.2-SNAPSHOT
          volumeMounts:
            - mountPath: /dst/plu-ws
              name: xplan-plu-workspace
              subPath: plu-workspace
        - name: init-xplan-plu-db
          image: grit/xplan-startup:2020.2
          command:
            [
              "/app/wait-for-postgres.sh",
              "-t",
              "0",
              "-h",
              "xplan-plu-db",
            ]
          env:
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASS
            - name: HOSTS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PORT
      volumes:
        - name: xplan-plu-workspace
          persistentVolumeClaim:
            claimName: xplan-plu-workspace-pvc
        - name: db-secret
          secret:
            secretName: xplan-pg-plu-secrect
#      imagePullSecrets:
#        - name: ci-pull-secret
