apiVersion: v1
kind: Secret
metadata:
  name: xplan-pg-plu-secrect
stringData:
  DB_HOST: xplan-plu-db
  DB_PORT: 5432
  DB_USER: plususer
  DB_PASS: plupass123!
  DB_DATABASE: planboxplu
  DB_SCHEMA: inspire
