apiVersion: v1
kind: Service
metadata:
  name: xplan-validator
  labels:
    app: xplan-validator
spec:
  selector:
    app: xplan-validator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    - protocol: TCP
      port: 8443
      targetPort: 8443