apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xplan-db-pvc
spec:
  storageClassName: ssd
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi